language: python
sudo: required
dist: xenial
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  #- pip install tox
   - pip install tox-travis

script:
  - tox
  #- pytest --cov=pystiebeleleltron
  #- coverage run --source icon_font_to_png -m py.test
  #- coverage report -m

#after_success:
  #- coveralls

#deploy:
  # https://docs.travis-ci.com/user/deployment/pypi/
  #- provider: pypi
  #  user: fucm
  #  password:
  #    secure: yourencryptedpwhere
  #  distributions: "sdist bdist_wheel"
  #  skip_existing: true
  #  on:
  #    tags: true
