name: Test python package

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
    - uses: actions/checkout@v2
    - name: Install uv
      uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: uv sync --locked --all-extras --dev
    - name: Run tests
      run: |
        uv run pytest \
          -qq \
          --durations=10 \
          -o console_output_style=count \
          -p no:sugar \
          test
